# Generated by Django 5.2.12 on 2026-04-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="coat_length",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="hypoallergenic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="lifespan",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="origin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="tags",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="temperament",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="weight",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
