# Generated by Django 5.2.12 on 2026-04-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "submissions",
            "0002_submission_coat_length_submission_hypoallergenic_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="coat_length",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="lifespan",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="origin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="submission",
            name="weight",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
