# Generated by Django 5.2.12 on 2026-04-09 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "[id]",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("origin", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                (
                    "temperament",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("calm", "Calm"),
                            ("playful", "Playful"),
                            ("affectionate", "Affectionate"),
                            ("independent", "Independent"),
                            ("social", "Social"),
                            ("energetic", "Energetic"),
                        ],
                        max_length=50,
                    ),
                ),
                ("lifespan", models.CharField(blank=True, max_length=30)),
                ("weight", models.CharField(blank=True, max_length=30)),
                ("coat_length", models.CharField(blank=True, max_length=30)),
                ("hypoallergenic", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="breeds/"),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareTip",
            fields=[
                (
                    "[id]",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("grooming", "Grooming"),
                            ("nutrition", "Nutrition"),
                            ("health", "Health"),
                            ("behavior", "Behavior"),
                            ("exercise", "Exercise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="care_tips",
                        to="breeds.breed",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
